-- Consulta SELECT executada em 2026-09-05 no projeto damp-forest-57346541,
-- branch production (br-snowy-violet-aymcvvvv), database neondb.
-- Retorna somente catalogos, hashes de migrations e agregados; nenhum segredo.
SELECT
  (SELECT jsonb_agg(jsonb_build_object('id', id, 'hash', hash, 'created_at', created_at) ORDER BY id) FROM drizzle.__drizzle_migrations) AS journal,
  (SELECT jsonb_build_object('credential_accounts', count(*), 'issuer_null', count(*) FILTER (WHERE issuer IS NULL), 'issuer_expected', count(*) FILTER (WHERE issuer = 'local:credential'), 'issuer_other', count(*) FILTER (WHERE issuer IS NOT NULL AND issuer <> 'local:credential'), 'rollback_0010_would_update', count(*) FILTER (WHERE issuer = 'local:credential')) FROM public.accounts WHERE provider_id = 'credential') AS credential_aggregates,
  (SELECT jsonb_agg(jsonb_build_object('table', table_name, 'column', column_name, 'type', data_type, 'nullable', is_nullable) ORDER BY table_name, column_name) FROM information_schema.columns WHERE table_schema = 'public' AND ((table_name = 'calculation_snapshots' AND column_name IN ('entity_id', 'idempotency_key')) OR (table_name = 'chat_conversations' AND column_name IN ('conversation_state', 'state_updated_at', 'state_metadata')) OR (table_name = 'ai_usage' AND column_name IN ('estimated_cost', 'cost_status', 'tool_execution_id')) OR (table_name = 'tool_executions' AND column_name IN ('estimated_cost', 'cost_status')) OR (table_name = 'ai_daily_budgets' AND column_name = 'estimated_cost_unknown_count'))) AS wave1_columns,
  (SELECT jsonb_build_object('unique', i.indisunique, 'valid', i.indisvalid, 'definition', pg_get_indexdef(i.indexrelid)) FROM pg_index i WHERE i.indexrelid = to_regclass('public.calculation_snapshots_idempotency_uidx')) AS snapshot_index,
  (SELECT jsonb_agg(jsonb_build_object('name', conname, 'validated', convalidated) ORDER BY conname) FROM pg_constraint WHERE conname IN ('ai_daily_budgets_nonnegative_check','ai_usage_cost_status_check','chat_conversations_state_check','tool_executions_cost_status_check')) AS wave1_constraints,
  (SELECT jsonb_build_object('superuser', rolsuper, 'bypassrls', rolbypassrls, 'login', rolcanlogin) FROM pg_roles WHERE rolname='app_runtime') AS runtime_role,
  (SELECT jsonb_agg(jsonb_build_object('table', c.relname, 'rls', c.relrowsecurity, 'force_rls', c.relforcerowsecurity, 'owner_is_runtime', pg_get_userbyid(c.relowner) = 'app_runtime') ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('calculation_snapshots','chat_conversations','ai_usage','tool_executions','ai_daily_budgets')) AS tenant_tables;
